"""核心模块"""

from app.core.async_downloader import (
    AsyncDownloader,
    AsyncLockDemo,
    AsyncQueueDemo,
    AsyncSemaphoreDemo,
    async_download_with_gather,
    async_download_with_queue,
    async_for_demo,
    async_timeout_demo,
)
from app.core.concept import (
    ConceptDemo,
    classify_task,
    demo_gil_impact,
    explain_concurrency_vs_parallelism,
)
from app.core.process_downloader import (
    ProcessDownloader,
    download_with_process_pool,
    download_with_processes,
    manager_demo,
    shared_array_demo,
    shared_queue_demo,
    shared_value_demo,
)
from app.core.progress import (
    AsyncProgressTracker,
    ProgressTracker,
    ThreadSafeProgress,
    create_progress_tracker,
)
from app.core.strategy import (
    Benchmark,
    ConcurrencyStrategy,
    StrategySelector,
    benchmark_download,
    choose_strategy,
    compare_strategies,
    get_strategy_recommendation,
)
from app.core.task import (
    DownloadResult,
    DownloadTask,
    TaskPriority,
    TaskStatus,
    create_download_task,
    create_task_batch,
)
from app.core.thread_downloader import (
    ThreadDownloader,
    download_with_as_completed,
    download_with_thread_pool,
    download_with_threads,
)
from app.core.thread_sync import (
    BarrierDemo,
    ConditionDemo,
    EventDemo,
    LockDemo,
    RLockDemo,
    SemaphoreDemo,
    ThreadSafeCounter,
)

__all__ = [
    "ConceptDemo",
    "classify_task",
    "demo_gil_impact",
    "explain_concurrency_vs_parallelism",
    "ThreadDownloader",
    "download_with_threads",
    "download_with_thread_pool",
    "download_with_as_completed",
    "LockDemo",
    "RLockDemo",
    "SemaphoreDemo",
    "EventDemo",
    "ConditionDemo",
    "BarrierDemo",
    "ThreadSafeCounter",
    "ProcessDownloader",
    "download_with_processes",
    "download_with_process_pool",
    "shared_queue_demo",
    "shared_value_demo",
    "shared_array_demo",
    "manager_demo",
    "AsyncDownloader",
    "async_download_with_gather",
    "async_download_with_queue",
    "AsyncLockDemo",
    "AsyncSemaphoreDemo",
    "AsyncQueueDemo",
    "async_for_demo",
    "async_timeout_demo",
    "ConcurrencyStrategy",
    "StrategySelector",
    "choose_strategy",
    "Benchmark",
    "benchmark_download",
    "compare_strategies",
    "get_strategy_recommendation",
    "DownloadTask",
    "DownloadResult",
    "TaskStatus",
    "TaskPriority",
    "create_download_task",
    "create_task_batch",
    "ProgressTracker",
    "ThreadSafeProgress",
    "AsyncProgressTracker",
    "create_progress_tracker",
]
