import { generateSidebar } from 'vitepress-sidebar'

export default generateSidebar([
  {
    documentRootPath: '/1-basics',
    scanStartPath: '',
    resolvePath: '/1-basics/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['05-examples', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/2-core',
    scanStartPath: '',
    resolvePath: '/2-core/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/3-advanced',
    scanStartPath: '',
    resolvePath: '/3-advanced/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/4-web',
    scanStartPath: '',
    resolvePath: '/4-web/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/5-ml',
    scanStartPath: '',
    resolvePath: '/5-ml/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/6-deep-learning',
    scanStartPath: '',
    resolvePath: '/6-deep-learning/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/7-projects',
    scanStartPath: '',
    resolvePath: '/7-projects/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/8-engineering',
    scanStartPath: '',
    resolvePath: '/8-engineering/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/9-langchain',
    scanStartPath: '',
    resolvePath: '/9-langchain/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['*_demo', '__pycache__', '.venv', 'venv', 'env'],
  },
  {
    documentRootPath: '/appendix',
    scanStartPath: '',
    resolvePath: '/appendix/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
])
