import { generateSidebar } from 'vitepress-sidebar'

const PYTHON_PROJECTS = [
  '__pycache__', '.venv', 'venv', 'env', '.pytest_cache',
  'python_basics', 'basic_syntax', 'string_demo', 'data_structures',
  'functions_demo', 'oop_demo', 'exceptions_demo', 'iterators_demo',
  'decorators_demo', 'type_hints_demo', 'modules_demo', 'builtin_demo',
  'flask_demo', 'fastapi_demo', 'async_demo',
  'ml_basics', 'deep_learning_demo',
  'code_quality', 'dev_tips', 'monitoring', 'project_mgmt',
  'langchain_basics', 'langgraph_basics', 'agent_basics',
  'langchain_advanced', 'langgraph_advanced',
  'agent_assistant', 'chatbot', 'doc_qa', 'multi_agent',
  'ai_chat_assistant',
]

export default generateSidebar([
  {
    documentRootPath: '/1-basics',
    scanStartPath: '',
    resolvePath: '/1-basics/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['05-examples', ...PYTHON_PROJECTS],
  },
  {
    documentRootPath: '/2-core',
    scanStartPath: '',
    resolvePath: '/2-core/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/3-advanced',
    scanStartPath: '',
    resolvePath: '/3-advanced/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/4-web',
    scanStartPath: '',
    resolvePath: '/4-web/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/5-ml',
    scanStartPath: '',
    resolvePath: '/5-ml/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/6-deep-learning',
    scanStartPath: '',
    resolvePath: '/6-deep-learning/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/7-projects',
    scanStartPath: '',
    resolvePath: '/7-projects/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
  {
    documentRootPath: '/8-engineering',
    scanStartPath: '',
    resolvePath: '/8-engineering/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/9-langchain',
    scanStartPath: '',
    resolvePath: '/9-langchain/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: PYTHON_PROJECTS,
  },
  {
    documentRootPath: '/appendix',
    scanStartPath: '',
    resolvePath: '/appendix/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
])
